version: '3'
services:
  btc:
    image: ruimarinho/bitcoin-core
    container_name: btc
    restart: always
    ports:
      - 18332:18332
      - 28332:28332
      - 28333:28333
    volumes:
      - ./bitcoind/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - bitcoin:/home/bitcoin/.bitcoin/ # data persistence


  lnd:
    image: lightninglabs/lnd:v0.12.0-beta
    container_name: lnd
    restart: always
    ports:
      - "10009:10009"
      - "9009:9735"
      - "9735:9735"
    volumes:
      - ./lnd/lnd.conf:/root/.lnd/lnd.conf
      - bitcoin:/home/bitcoin/.bitcoin/ 
      - bitcoin:/root/.lnd/

volumes:
  bitcoin: